name: test tag created
on:
  push:
    tags:
      - test-202[0-9][0-1][0-9][0-3][0-9][0-2][0-9][0-5][0-9]
jobs:
  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
