name: test tag created
on:
  push:
    tags:
      - test-202[0-9][0-1][0-9][0-3][0-9][0-2][0-9][0-5][0-9]
jobs:
  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -f dockerfiles/liff.Dockerfile -t ${{ secrets.ACR_NAME }}.azurecr.io/cafe-seat-finder-line-bot:test .
          docker tag ${{ secrets.ACR_NAME }}.azurecr.io/cafe-seat-finder-line-bot:test ${{ secrets.ACR_NAME }}.azurecr.io/cafe-seat-finder-line-bot:${{ github.ref_name }}
      - name: push images
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/cafe-seat-finder-line-bot:test
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/cafe-seat-finder-line-bot:${{ github.ref_name }}
